#!/bin/sh

# Post Artix Minimal Install Commands

### VARIABLES ###

NAME="daniel"

DRIVERS="nvidia"

DWMCONFIG="https://github.com/danpellegrino/dwm"
STCONFIG="https://github.com/danpellegrino/st"
DMENUCONFIG="https://github.com/danpellegrino/dmenu"

### FUNCTIONS ###

setupuser(){
	useradd -m -g wheel "$NAME"
	passwd "$NAME"
}

editpermissions(){
	sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers
}

enableservices(){
	
	# Network Service
	pacman -S networkmanager networkmanager-runit
	ln -s /etc/runit/sv/bluetoothd /run/runit/service/
	sv start networkmanager

	# Printing Service
	pacman -S cups cups-runit
	ln -s /etc/runit/sv/cupsd /run/runit/service/
	sv start cupsd

	# Cron Jobs
	pacman -S cronie cronie-runit
	ln -s /etc/runit/sv/cronie /run/runit/service/
	sv start cronie
}

driverinstall(){
	pacman -S "$DRIVERS"
}

setupxorg(){
	pacman -S xorg-server xorg-xinit libx11 libxft libxinerama noto-fonts
}

setupenvironment(){
	pacman -S git

	git clone "$DWMCONFIG"
	git clone "$STCONFIG"
	git clone "$DMENUCONFIG"


	# NOTE
	# Compile all packages
	
	# template for xinitrc can be found at /etc/X11/xinit/xinitrc
	# you'll have to remove all the 5 lines with xterm related things at the bottom though
	echo "exec dwm" >> /home/$NAME/.xinitrc

	echo "startx" >> /home/$NAME/.bash_profile
}

### ACTUAL SCRIPT ### 

setupuser

editpermissions

driverinstall

setupxorg

setupenvironment

### PACKAGES INSTALLED AFTER ###
# xorg-xrandr; used for configuring monitor resolutions, refresh rate, etc. through command-line
# btrfs-progs; btrfs utilities
# G https://github.com/Morganamilo/paru ; AUR helper
# A librewolf-bin; browser
# A timeshift;
# A grub-btrfs
# Now anytime timeshift creates a backup run 'grub-mkconfig -o /boot/grub/grub.cfg' and it will create a snapshot on grubs boot screen
#
# Extra
# wireplumber
# pipewire-pulse
# pavucontrol
# openssh
# neofetch
# vim
# neovim
# arandr
# xclip
#
# I set up auto login in /etc/runit/sv/agetty-tty1/conf
#
# feh
# bluez
# bluez-runit
# bluez-utils
#
# made a script to connect my headphones called connect_headphones in ~/.local/bin/
# ^ had to add ~/.local/bin into my $PATH in ~/.bashrc
#
# zsh
# zsh-completions
# set up .xinitrc, .xprofile, etc.. into ~/.config
# found -> https://unix.stackexchange.com/questions/672448/how-can-i-change-the-location-of-xinitrc-and-zsh-files
# same with .zinitrc and .zprofile
# G dwmblocks
# 
# Had to edit bios clock since it was off by ~4 hours
#
# picom
# fzf
# xorg-xset
# unzip
#
# 'JetBrainsMono Nerd Font' from https://www.nerdfonts.com/font-downloads
#
# added multimedia + volume keys to dwm
#
# playerctl
# os-prober
#
# installed starship with curl -sS https://starship.rs/install.sh | sh
#
# enabled multilib (lib32 in artix)
# /etc/pacman.conf
#
# ### UNCOMMENT(/etc/pacman.conf) ### 
# [lib32]
# Include = /etc/pacman.d/mirrorlist
#
# ### APPEND(/etc/pacman.conf) ### 
# [universe]
# Server = https://universe.artixlinux.org/$arch
# Server = https://mirror1.artixlinux.org/universe/$arch
# Server = https://mirror.pascalpuffke.de/artix-universe/$arch
# Server = https://mirrors.qontinuum.space/artixlinux-universe/$arch
# Server = https://mirror1.cl.netactuate.com/artix/universe/$arch
# Server = https://ftp.crifo.org/artix-universe/$arch
# Server = https://artix.sakamoto.pl/universe/$arch
#
# sudo pacman-Syu
# artix-archlinux-support
# 
# ### APPEND(/etc/pacman.conf) ###
# #[testing]
# #Include = /etc/pacman.d/mirrorlist-arch
#
#
# [extra]
# Include = /etc/pacman.d/mirrorlist-arch
#
#
# #[community-testing]
# #Include = /etc/pacman.d/mirrorlist-arch
#
#
# [community]
# Include = /etc/pacman.d/mirrorlist-arch
#
#
# #[multilib-testing]
# #Include = /etc/pacman.d/mirrorlist-arch
#
#
# [multilib]
# Include = /etc/pacman.d/mirrorlist-arch
#
# sudo pacman -Syu
# pacman-key --populate archlinux'
#
# A discord_arch_electron
# steam -> lib32-nvidia-utils (all from lib32 repo)
